config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#home"
  get "about", to: "home#about"
  get "signup", to: "users#new"
  resources :users, except: [:new]
  resources :articles
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       length: { minumum: 5, maximum: 25 }

  VALID_EMAIL_REGEX = /\A([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 8, maximum: 25 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    # !! turns current_user into a boolean
    # essentially changing it to an if statement and checking if true then return such else return false
    !!current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def new
    if logged_in?
      @article = Article.new
    else
      flash[:warning] = "you must login to create an article"
      redirect_to login_path
    end
  end

  def edit
    user = @article.user
    if (user.username != current_user.username)
      flash[:warning] = "You cannot edit someone else's article"
      redirect_to root_path
    end
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def update
    if (@article.update(article_params))
      flash[:success] = "Article was successfully edited"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def create
    # render plain: params[:article].inspect // allows you to view what is being passed to article
    @article = Article.new(article_params)
    @article.user = helpers.current_user if helpers.logged_in?
    # @article.save
    # redirect_to article_path(@article)
    if (@article.save)
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def show
    @user = @article.user
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was deleted"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if (user && user.authenticate(params[:session][:password]))
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully."
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Something is wrong with your login details"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:warning] = "Logged Out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def create
    @user = User.new(user_params)

    if (@user.save)
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Alpha Blogs, #{@user.username}"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    if (logged_in? && current_user.username != @user.username)
      flash[:warning] = "You cannot edit someone else's profile"
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "user has been updated."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circler")
  end

  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end

  # def logged_in?
  #   # !! turns current_user into a boolean
  #   # essentially changing it to an if statement and checking if true then return such else return false
  #   !!current_user
  # end
end

app/views/articles/_articles.html.erb
<% articles.each do |article| %>
  <div class="card" >
    <div class="card-body">
      <h5 class="card-title"><%= link_to article.title, article %></h5>
      <h6 class="card-subtitle mb-2 text-muted">By: <%= link_to article.user ? article.user.username : "Unknown", user_path(article.user) %></h6>
      <h6 class="card-subtitle mb-2 text-muted"><small>Created: <%= time_ago_in_words(article.created_at) %> ago</small> | <small>Updated: <%= time_ago_in_words(article.updated_at) %> ago</small></h6>
      <p class="card-text"><%= truncate(article.description, length: 100) %></p>
      <%= link_to "Show", article_path(article), class: "card-link btn-sm btn-success" %>
      <% if logged_in? && current_user.username == article.user.username %>
        <%= link_to "Edit", edit_article_path(article), class: "card-link btn-sm btn-primary" %>
        <%= link_to "Delete", article, method: :delete, data: { confirm: "Are you sure?" }, class: "card-link btn-sm btn-danger" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
  <%= render "shared/errors", obj: @article %>

  <%= form_for @article do |post| %>
    <div class="article_title_area form-group">
      <%= post.label :title %>
      <br>
      <%= post.text_field :title, class: "form-control" %>
    </div>
    <div class="article_description_area form-group">
      <%= post.label :description %>
      <br>
      <%= post.text_area :description, rows: 5, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= post.submit class: "btn btn-danger" %>
      <%= link_to "Back", articles_path, class: "btn btn-danger" %>
    </div>
  <% end %>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Edit Article</title>
  </head>
  <body>
    <main>
      <h1 class="article-title">Edit an Article</h1>
      </br>
      <%= render "form" %>
    </main>
  </body>
</html>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Article Index</title>
</head>
<body>
  <!-- 
  <div class="articles-table">
    <table class="table table-dark">
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>By</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Actions</th>
      </tr>
      -->
      <div class="digg_pagination mb-4">
       <%= will_paginate @articles %>
      </div>
      <div class="article-grid">
        <%= render "articles", articles: @articles %>
      </div>
      <!-- 
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to article.title, article %></td>
          <td><%= link_to truncate(article.description, length: 100), article %></td>
          <td><%= link_to article.user ? article.user.username : "Unknown", user_path(article.user) %></td>
          <td><%= time_ago_in_words(article.created_at) %> ago</td>
          <td><%= time_ago_in_words(article.updated_at) %> ago</td>
          <td><%= link_to "Edit", edit_article_path(article) %></td>
          <td><%= link_to "Show", article_path(article) %></td>
          <td><%= link_to "Delete", article, method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </table>
  </div>
  -->
  <div class="digg_pagination mt-4 mb-4">
    <%= will_paginate @articles %>
  </div>
  <div class="mobile-view-articles">
    <%= render "articles", articles: @articles %>
  </div>
</body>
</html>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
  </head>
  <body>
    <main>
      <h1 class="article-title">Create an Article</h1>
      <br>
      <%= render "form" %>     
    </main>
  </body>
</html>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Article Show</title>
  </head>
  <body>
    <div class="container show-container">
      <div class="card" style=<%= @article.description.length > 100 ? "width:50rem;" : "width:25rem;" %>>
        <div class="card-body">
          <h5 class="card-title"><%= @article.title %></h5>
          <div class="subtitle-container">
            <h6 class="card-subtitle mb-2 text-muted">
              <%= gravatar_for @user, size: 55 %>
              &nbsp;
              <%= link_to @user ? "By: #{@user.username}" : "By: Unknown", @user ? user_path(@user) : href = "#" %>
            </h6>
            
          </div>
          <p class="card-text"><%= @article.description %></p>
          <% if logged_in? && @user.username == current_user.username %>
            <%= link_to "Edit", edit_article_path(@article), class: "card-link btn btn-primary" %>
            <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure ?" }, class: "card-link btn btn-danger" %>
          <% end %>
          <%= link_to "View All Articles", articles_path, class: "card-link btn btn-primary" %>
        </div>
      </div>
    </div>
      <!-- 
        <ul class="article-list">
          <li>Title: <h3 class="article-title"><%= @article.title %></h3></li>
          <li>Description:  <p> <%= @article.description %> </p> <li>
          <button><%= link_to "Edit", edit_article_path(@article) %></button>
        </ul>
      -->
  </body>
</html>

app/views/home/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
  </head>
  <body>
    <main>
      <div class="content">
        <p class="text">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam fuga
          et maxime aut consequatur modi in consectetur molestiae ex, ad eius
          aperiam praesentium tempora nulla officia asperiores. Tenetur
          recusandae, aperiam optio soluta consectetur culpa natus hic aliquam
          eligendi impedit enim cum alias eum deserunt. Eum quisquam voluptatum
          optio vitae sit reprehenderit reiciendis eligendi nobis, cupiditate
          veniam, quas officia voluptatem, quam perferendis id consectetur.
          Consequuntur, asperiores! Quasi impedit nisi, quisquam deserunt
          dolorum consequatur, repellat harum ducimus provident quos temporibus
          animi non excepturi atque officiis unde id ullam illum quis explicabo
          dolores. Harum ex reprehenderit suscipit mollitia natus enim dolores
          temporibus minima possimus tempora corporis minus nostrum ipsam
          excepturi, amet corrupti. Totam non illo ad natus necessitatibus
          corporis quidem rem, animi commodi quisquam sed laborum illum nisi ex
          est? Explicabo, inventore! Nobis voluptate fuga sed. Pariatur iusto
          aperiam eos nam ratione quisquam voluptatem excepturi rerum beatae
          vitae ad expedita ab illo sed recusandae voluptatibus nobis, provident
          dolorum consectetur earum neque! Praesentium excepturi necessitatibus
          eveniet officia tenetur? Ab nam, delectus nobis quis iusto voluptates
          ad magni iste, incidunt distinctio suscipit voluptatibus esse
          laudantium explicabo! Nulla cupiditate est sunt fuga, ut ea enim
          dolorum illum rerum vitae ullam cum delectus hic? Eos officiis iure
          eaque soluta excepturi repudiandae, inventore porro perspiciatis
          labore repellat praesentium ea. Corrupti ipsa eligendi, consequatur
          quidem temporibus voluptates sed dolorum vero aperiam sapiente commodi
          porro dignissimos laboriosam magni suscipit adipisci a! Doloremque
          laudantium, quas dolore eum excepturi, assumenda corrupti vel possimus
          voluptates aperiam exercitationem dolor aliquid velit laboriosam
          aspernatur quia optio accusamus, sed voluptate eos illo tempora ipsum
          expedita recusandae. Tenetur, nostrum similique corporis beatae autem
          explicabo error nemo dignissimos sit molestias voluptate, ex laborum
          labore reiciendis harum voluptatibus blanditiis quibusdam? Labore
          repudiandae amet esse necessitatibus modi hic! Laudantium accusamus
          reprehenderit, velit vero ut veniam. Non modi aut debitis ab
          similique. Voluptate distinctio accusantium nulla. Nemo sint ipsam
          quasi accusantium ut nesciunt accusamus porro animi. Asperiores
          ratione eveniet repellat deleniti ipsa voluptatibus quod ipsum
          perspiciatis sed voluptas totam saepe, aliquid vitae adipisci possimus
          autem harum, eaque hic ut dignissimos numquam. Dicta similique,
          laborum deleniti sit ab, accusamus esse maxime enim mollitia atque
          illum. Assumenda voluptates voluptas aperiam consequatur suscipit
          officiis eum libero modi cum! Commodi dolores voluptatem, repudiandae
          molestias placeat fugit adipisci eveniet rerum animi, omnis a voluptas
          inventore suscipit dolore, id cum harum quos dignissimos eaque est.
          Magni cumque, facilis, quibusdam harum sunt, neque sit nihil autem
          ducimus ex at numquam! Saepe perferendis ex aut unde similique
          reiciendis, illum animi a dolorem, aperiam perspiciatis ut explicabo
          rem libero, magni culpa iusto delectus pariatur soluta aliquam ipsum
          maiores. Ab quaerat ullam aliquid dolore nobis, repellendus quae
          inventore odio, molestias pariatur explicabo laboriosam laudantium
          laborum, corporis consectetur doloribus? Nam, eos perspiciatis
          provident facilis eum, corporis est totam molestiae molestias tempora
          facere obcaecati. Ducimus quia quis magnam vero neque in deleniti,
          corporis nisi consectetur perferendis, nobis pariatur! Libero,
          doloremque numquam, pariatur accusamus sint beatae ut corrupti ab
          necessitatibus a aperiam! Nesciunt iste laborum in officia hic,
          quisquam consequatur nam nostrum et fugit placeat ullam illum!
          Adipisci iste deleniti ducimus sequi saepe esse porro dolore
          exercitationem ab pariatur ipsa, magni nemo quasi obcaecati
          praesentium recusandae magnam. Qui labore odit mollitia similique fuga
          officiis alias dicta nesciunt facilis assumenda iusto cupiditate
          aspernatur, quis, ratione unde facere sunt vero! Pariatur accusantium
          nobis nam sint eveniet quibusdam? Quia neque cumque eligendi quaerat a
          ad fuga tempore laborum illum nesciunt aut ipsam voluptates quos
          necessitatibus, similique amet, reiciendis id sapiente deleniti
          expedita, doloribus nobis! Totam dolores labore sequi magnam
          cupiditate explicabo, sit aliquid maiores impedit, dolor quia nam
          ducimus eveniet dolorem ad id. Quas neque quos animi ipsam commodi at
          laborum pariatur, rerum voluptates facilis! Deserunt numquam officiis
          repudiandae quod mollitia, quae totam pariatur eum velit ducimus saepe
          harum earum fuga vel perferendis quibusdam. Vel corporis, laboriosam
          ipsa reiciendis maiores reprehenderit aspernatur quibusdam, modi,
          necessitatibus consequatur enim fugit quaerat amet aliquid rem?
          Recusandae assumenda expedita ducimus aliquam tempora adipisci,
          aliquid alias libero omnis neque? Sed nihil nisi quis vel, incidunt
          ullam. Debitis similique cum voluptatibus sapiente, saepe id, a nihil
          aut modi eum dicta consequatur maiores quidem at omnis praesentium
          placeat mollitia quasi! Tempore molestiae amet, id perferendis itaque,
          cum provident repellat doloribus saepe harum eveniet numquam quaerat
          illo fugiat tempora illum debitis totam repudiandae reiciendis labore
          ipsa fugit? Animi est omnis, exercitationem quas optio distinctio!
          Asperiores dolore repellendus molestiae corrupti qui, quaerat eveniet
          necessitatibus aut similique laudantium consequatur expedita corporis
          aspernatur error nesciunt saepe culpa eaque delectus sint voluptate
          optio nisi possimus? Magnam expedita itaque, aut deserunt natus,
          laboriosam vero deleniti, ratione iste modi id reiciendis numquam
          accusamus perspiciatis dolore pariatur facere quis porro! Quibusdam
          quis tempora ad ea optio, ipsa iste sequi perferendis exercitationem,
          eos similique ipsum assumenda eveniet illum? Officiis doloribus
          similique porro, suscipit sunt illo possimus reprehenderit dolor omnis
          commodi quidem est quos. Praesentium est architecto quisquam facilis
          sed debitis necessitatibus sapiente quas ab odio expedita, eos, magni
          vel at error perspiciatis veniam eum, mollitia cum nihil accusamus
          nobis minima consectetur! Culpa asperiores consequuntur harum, quo
          deleniti tenetur ipsam repellat explicabo voluptates consequatur
          excepturi illo omnis, corrupti doloribus? Eius omnis ullam quo tenetur
          consequuntur fugit modi excepturi eligendi similique rem soluta unde
          exercitationem sunt dolorem totam, dolor delectus ea! Placeat facilis
          laboriosam aut, quia tempore, sapiente suscipit voluptates atque velit
          dolorem soluta earum iste vero mollitia culpa aspernatur unde aperiam.
          Facilis beatae praesentium eaque, assumenda ratione sequi aperiam
          placeat soluta! Reiciendis repellat repellendus ea facilis? Dolorem,
          perferendis omnis sed inventore sint nostrum quia, hic ullam veritatis
          similique ratione nemo aliquam natus est eligendi atque placeat,
          minima excepturi. Veniam, corrupti? Porro et, tenetur adipisci ducimus
          nulla placeat libero, minus dolor consectetur, ratione commodi cum
          enim doloribus rem iste perspiciatis nemo a. Perferendis, saepe
          voluptate. Fugit magnam obcaecati quod necessitatibus quia libero, vel
          consequuntur? Sunt ad quod fugiat odio eligendi, ab voluptatem quas
          natus modi nemo! Omnis consectetur modi voluptatibus obcaecati
          provident facere tenetur repellendus minima? Optio cupiditate non
          itaque ratione quibusdam nemo debitis beatae harum. Ratione obcaecati,
          sed omnis deserunt mollitia tempore dolore provident?
        </p>
      </div>
    </main>
  </body>
</html>

app/views/home/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home</title>
  </head>
  <body>
    <div class="jumbotron center">
      <h1>Alpha Blog</h1>
      <%= link_to "Sign up now", signup_path, class: "btn btn-primary btn-lg btn-xlarge" %>
    </div>
  </body>
</html>

app/views/layouts/_flash.html.erb
<% flash.each do |name, message| %>
  <!--
    <ul class="flash-message-display-area">
      <li class="flash-message alert alert-success">
        <%= message %>
      </li>
    </ul>
  -->
  <div class="container flash-message-container">
    <p class='flash-message alert alert-<%= "#{name}" %>'>
      <a href="#" class="close close-flash-message" data-dismiss="alert">&#215;</a>
      <%= message %>
    </p>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright &copy; 2020
  </small>
  <nav>
    <ul>
      <li>
        <%= link_to "About", about_path %>
      </li>
      <li>
        <%= link_to "Home", root_path %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark sticky-top">
  <% # <a class="navbar-brand" id="logo" href="/articles">Alpha-Blogs</a> %>
  <%= link_to "Alpha-Blogs", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% # <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a> %>
        <%= link_to "Home", root_path, class: "nav-link links" %>
      </li>
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link links" %>
      </li>
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link links" %>
      </li>
      <!--
      <li class="nav-item">
        <a class="nav-link links" href="/about">About</a>
      </li>
      -->
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Create Article", new_article_path, class: "nav-link links" %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, class: "nav-link links", method: :delete %>
        </li>
        <li class="nav-item">
          <%= link_to current_user.username, user_path(current_user), class: "nav-link links" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link links" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign-Up", signup_path, class: "nav-link links" %>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle links" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create Article", new_article_path, class: "dropdown-item" %>
          <% if logged_in? %>
             <%= link_to "Logout", logout_path, class: "dropdown-item", method: :delete %>
          <% else %>
            <%= link_to "Login", login_path, class: "dropdown-item" %>
          <% end %>
          <!--
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
          -->
        </div>
      </li>
    </ul>
    <!--
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" id="search-btn" type="submit">Search</button>
    </form>
    -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %> <%= csp_meta_tag %> 
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %> 
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <div class='main-container'>
      <%= render "layouts/navigation" %>
      <%= render "layouts/flash" %> 
      <div class="container">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
    <div class="debug" align="center">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edit User</title>
  </head>
  <body>
    <h1>Edit Your User Info</h1>
    <%= render "form", state: "edit" %>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Users</title>
</head>
<body>
  <div align="center" class="users-index-container">
    <h1 class="user-index-title">All Alpha Bloggers</h1>
    <div class="digg_pagination mb-4">
       <%= will_paginate @users %>
    </div>
    <% @users.each do |user| %>
      <ul class="listing">
        <div class="card row">
          <%= link_to gravatar_for(user), user_path(user) %>
          <div class="card-body col-md-4 col-md-offset-4">
            <li>
              <h5 class="card-title"><%= link_to user.username, user_path(user) %></h5>
            </li>
            <li>
              <h6 class="card-subtitle mb-2">
                <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
              </h6>
            </li>
            <aside class="buttons-container">
              <li>
                <%= link_to "View Profile", user_path(user), class: "btn btn-success" %>
              </li>
              <% if logged_in? && current_user.username == user.username %>
                <li>
                  <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-warning" %>
                </li>
              <% end %>
            </aside>
            <li>
              <small>Joined <%= time_ago_in_words(user.created_at) %></small>
            </li>
          </div>
        </div>
      </ul>
    <% end %>
    <div class="digg_pagination mb-4">
       <%= will_paginate @users %>
    </div>
  </div>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div class="users-container">
  <h1 class="text-center mt-4"> Welcome <%= @user.username %>'s Page</h1>
  <div class="row justify-content-center">
    <div class="col-md-4 col-md-offset-4 center">
      <%= gravatar_for @user, size: 200 %>
    </div>
  </div>
  <% if logged_in? && current_user.username == @user.username %>
    <div class="user-show-btn-container">
      <%= link_to "Edit your Profile", edit_user_path(@user), class: "btn btn-outline-warning user-show-edit-btn" %>
    </div>
  <% end %>
  <h4 class="user-show-h4">
    <%= @user.username %>'s articles
  </h4>
  <div class="user-articles align-self-center">
    <div class="digg_pagination mb-4">
       <%= will_paginate @articles %>
    </div>
    <%= render "articles/articles", articles: @articles %>
    <div class="digg_pagination mb-4 mt-4">
       <%= will_paginate @articles %>
    </div>
  </div>
  </div>
</body>
</html>